Add handling for elusive bugs (one in particular)
I have no idea what is causing the "Internal Server Error" where one
f&@%ing paste won't format. The very same paste works _fine_ on my local
development copy, and even after fixing _one_ bug, I'm left with another
I can't quite place. The traceback, for reference:

Traceback (most recent call last):
  File "pokepaste.py", line 179, in application
    response = format_paste(paste[0], paste[1]).encode('utf-8')
  File "pokepaste.py", line 123, in format_paste
    if line[0] == '-' and line[1:].strip() in move_data:
IndexError: string index out of range

In the meantime, better error handling should turn this from an
experience-ruining problem to an acceptable one.